import type {Metadata} from "next";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import {
    AppShell,
    AppShellHeader,
    AppShellMain,
    ColorSchemeScript, Container,
    createTheme,
    MantineProvider
} from "@mantine/core";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
// palaviajeros logo color: #ff4c5c Todo: to add later
const palaViajerosTheme = createTheme({
    primaryColor: 'red',
    breakpoints: {
        xs: '30em',
        sm: '48em',
        md: '64em',
        lg: '74em',
        xl: '90em',
    },
});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <ColorSchemeScript/>
        </head>
        <body>
        <MantineProvider theme={palaViajerosTheme}>
            <AppShell header={{height: {base: 36, sm: 48, lg: 60}}}>
                <AppShellHeader>
                    <Navbar/>
                </AppShellHeader>
                <AppShellMain>
                    <Container size="xl" mt={"lg"}>
                        {children}
                    </Container>
                    <Footer/>
                </AppShellMain>
            </AppShell>
        </MantineProvider>
        </body>
        </html>
    );
}
