import type {Metadata} from "next";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import {ColorSchemeScript, createTheme, MantineProvider} from "@mantine/core";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
// palaviajeros logo color: #ff4c5c Todo: to add later
const palaViajerosTheme = createTheme({
    primaryColor: 'red',
});

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <ColorSchemeScript/>
        </head>
        <body>
        <MantineProvider theme={palaViajerosTheme}>
            <Navbar/>
            {children}
            <Footer/>
        </MantineProvider>
        </body>
        </html>
    );
}
